### ISSUE TITLE
Signup By Email/ Mobile and OTP

### ISSUE THREAD

**Issue by ShubhamJoshi-1994** [nobejs/access#7]
We need support for the following Authentication flows:

* [x] Signup from Email and OTP
* [x] Signup from Mobile and OTP
* [x] Resend Confirmation Code
* [x] Verify Email
* [x] Verify Mobile

**Comment by rjvim** [comment]
@ShubhamJoshi-1994 The stories and endpoints are implemented.

1. You can check our Readme here for more information: https://github.com/nobejs/access
2. You can import our postman collection (public) and play around with it

**Comment by rjvim** [comment]
@ShubhamJoshi-1994 Can this issue be closed?

**Comment by ShubhamJoshi-1994** [comment]
Yes, @rjvim checked the code, and we can close this issue.
